env:
  global:
    CONAN_PRINT_RUN_COMMANDS: 1

    CONAN_USERNAME: odant
    CONAN_REFERENCE: zlib/1.2.11

    CONAN_UPLOAD: https://api.bintray.com/conan/odant/conan
    CONAN_LOGIN_USERNAME: dvetutnev
    CONAN_STABLE_BRANCH_PATTERN: release/*

linux: &linux_build
  os: linux
  sudo: false
  dist: trusty
  language: python
  python: "3.6"
  virtualenv:
    system_site_packages: true
  services:
    - docker

install:
  - pip3 install conan
  - pip3 install conan_package_tools
  - conan user

script:
  - echo "Script step"