skip_tags: true

environment:
  PYTHON: C:\\Python36
  PYTHON_VERSION: 3.6.3
  PYTHON_ARCH: 32

  CONAN_PRINT_RUN_COMMANDS: 1

  CONAN_USERNAME: odant
  CONAN_REFERENCE: zlib/1.2.11

  CONAN_ARCHS: x86_64
  CONAN_BUILD_TYPES: Debug
  CONAN_VISUAL_RUNTIMES: MDd
  CONAN_VISUAL_TOOLSETS: v141_xp

  CONAN_UPLOAD: https://api.bintray.com/conan/odant/conan
  CONAN_LOGIN_USERNAME: dvetutnev
  CONAN_STABLE_BRANCH_PATTERN: release/*
  
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CONAN_VISUAL_VERSIONS: 15

install:
  - git submodule update --init --recursive

  - set PATH=%PYTHON%;%PYTHON%\\Scripts\\;%PATH%
  - pip install conan
  - pip install conan_package_tools

  - conan user
  - conan config set log.print_run_commands=True
  
build: false
  
test_script:
  - python build.py

