message(STATUS "Conan: Advance FindZLIB.cmake, adjusting variable ZLIB_LIBRARY")

find_library(ZLIB_LIBRARY
    NAMES ${CONAN_LIBS_ZLIB}
    PATHS ${CONAN_LIB_DIRS_ZLIB}
    NO_DEFAULT_PATH
)

include(${CMAKE_ROOT}/Modules/FindZLIB.cmake)

message(STATUS "Conan: ZLIB_INCLUDE_DIRS => ${ZLIB_INCLUDE_DIRS}")
message(STATUS "Conan: ZLIB_LIBRARIES => ${ZLIB_LIBRARIES}")
get_target_property(INTERFACE_INCLUDE_DIRECTORIES ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES)
message(STATUS "Conan: ZLIB::ZLIB INTERFACE_INCLUDE_DIRECTORIES => ${INTERFACE_INCLUDE_DIRECTORIES}")
get_target_property(IMPORTED_LOCATION ZLIB::ZLIB IMPORTED_LOCATION)
message(STATUS "Conan: ZLIB::ZLIB IMPORTED_LOCATION => ${IMPORTED_LOCATION}")
